import type { Locale } from "@/lib/i18n";

/** Interface and page copy. PENDING: final approval of wording by 24SHOOTS. */
const es = {
  meta: {
    homeTitle: "24SHOOTS — Estudio creativo de contenido y comunicación visual · Valencia",
    homeDescription:
      "Estudio creativo de contenido y comunicación visual para marcas en Valencia. Vídeo y fotografía para eventos corporativos, contenido de marca y campañas.",
    orgDescription:
      "Estudio creativo de contenido y comunicación visual con base en Valencia. Vídeo y fotografía para eventos corporativos, contenido de marca y campañas.",
  },
  nav: { work: "Trabajo", services: "Servicios", studio: "Estudio", contact: "Contacto", cta: "Hablemos", menu: "Menú", close: "Cerrar", skip: "Saltar al contenido", home: "Inicio", language: "English", languageShort: "EN" },
  hero: {
    eyebrow: "Estudio creativo · Valencia",
    title: "Imagen con idea.",
    lead: "Contenido y comunicación visual para marcas: eventos corporativos, contenido de marca y campañas. Pensado, rodado y montado por el mismo equipo.",
    primary: "Cuéntanos tu proyecto",
    secondary: "Ver trabajo",
    reelLabel: "Montaje de trabajos recientes",
    pause: "Pausar montaje",
    play: "Reproducir montaje",
    shot: "Plano",
    viewCase: "Ver proyecto",
  },
  work: {
    title: "Trabajo seleccionado",
    intro: "Cinco proyectos. Cada uno, un momento importante para una organización, contado en imagen.",
    all: "Todo el trabajo",
    view: "Ver proyecto",
    count: (n: number) => `${String(n).padStart(2, "0")} proyectos`,
  },
  day: {
    kicker: "Un día, todo el año",
    title: "Un evento dura un día. Lo que se cuenta de él, todo el año.",
    body: "Un aniversario, una gala, un congreso: momentos que una organización prepara durante meses y que duran unas horas. Nuestro trabajo es que se puedan seguir contando después, en la web, en redes, en la comunicación interna o en la próxima presentación.",
    sheetCaption: "Huhtamaki · 50 aniversario. Doce planos del mismo día.",
    fromOneShoot: "De un mismo rodaje pueden salir",
    outputs: ["La película del evento", "Cortes verticales para redes", "Una selección de fotografía", "Piezas cortas para comunicación interna o prensa"],
  },
  servicesBlock: { title: "Qué hacemos", capabilities: "Rodaje · Dron · Fotografía · Montaje · Color · Sonido · Versiones para redes" },
  clients: {
    title: "Con quién hemos trabajado",
    agencies: "También producimos dentro del equipo de agencias y productoras de eventos.",
  },
  contactBlock: {
    title: "Cuéntanos tu proyecto.",
    lead: "Qué es, cuándo es y qué necesitas contar. Te responde una persona del equipo.",
    direct: "O escríbenos directamente",
  },
  form: {
    name: "Nombre",
    email: "Email",
    company: "Empresa u organización",
    type: "Tipo de proyecto",
    types: ["Evento", "Contenido de marca", "Campaña", "Otra cosa"],
    message: "¿Qué tienes entre manos?",
    messageHint: "Por ejemplo: aniversario de la empresa en junio, unas 300 personas, queremos una película y piezas para redes.",
    date: "Fecha o plazo, si lo hay",
    optional: "opcional",
    required: "obligatorio",
    submit: "Enviar",
    sending: "Enviando…",
    privacy: "Usaremos tus datos solo para responder a esta solicitud.",
    privacyLink: "Política de privacidad",
    successTitle: "Recibido.",
    success: (email: string) => `Te responderemos a ${email}. Mientras tanto, puedes ver más trabajo.`,
    errorTitle: "No se ha podido enviar.",
    errorBody: "Escríbenos directamente a",
    errors: {
      name: "Escribe tu nombre.",
      email: "Revisa el email: parece incompleto.",
      message: "Cuéntanos un poco más (al menos 20 caracteres).",
      rate: "Demasiados envíos seguidos. Espera un minuto o escríbenos por email.",
      generic: "Ha fallado el envío.",
    },
    summary: "Revisa los campos marcados.",
  },
  case: {
    client: "Cliente",
    type: "Tipo",
    when: "Fecha",
    with: "Con",
    format: "Formato",
    play: "Reproducir película",
    duration: "Duración",
    shows: "Qué cuenta la película",
    stills: "Fotogramas",
    next: "Siguiente proyecto",
    cta: "¿Tienes un momento así por delante?",
    ctaButton: "Hablemos",
    area: "Área",
  },
  servicesPage: {
    title: "Servicios",
    intro: "Tres formas de trabajar con nosotros. En todas, la misma idea: que la imagen sirva para comunicar algo concreto.",
    problem: "El problema",
    approach: "Cómo lo hacemos",
    capabilities: "Capacidades",
    deliverables: "Qué se entrega",
    related: "Trabajo relacionado",
    faq: "Preguntas frecuentes",
    cta: "Cuéntanos tu proyecto",
  },
  studio: {
    title: "Estudio",
    lead: "24SHOOTS es un estudio creativo de contenido y comunicación visual con base en Valencia. Trabajamos para marcas, instituciones y agencias de eventos: pensamos, rodamos y montamos piezas de vídeo y fotografía que una organización puede usar para contar lo que hace.",
    howTitle: "Cómo trabajamos",
    how: [
      { t: "Antes", d: "Entendemos qué hay que contar, a quién y dónde se va a ver, antes de decidir cómo grabarlo." },
      { t: "Durante", d: "Rodamos con un plan pactado: qué momentos importan, qué personas deben aparecer y qué formatos hacen falta." },
      { t: "Después", d: "Montaje, color y sonido pensados para cada canal: la pieza principal y todas las que salen de ella." },
    ],
    agenciesTitle: "Para agencias y productoras",
    agencies: "Parte de nuestro trabajo se hace dentro del equipo de agencias y productoras de eventos. Nos encargamos del audiovisual para que ellas puedan centrarse en el evento.",
    clientsTitle: "Clientes",
  },
  contactPage: {
    title: "Cuéntanos tu proyecto",
    lead: "Cuanto más concreto, mejor: qué es, cuándo es, para quién y dónde se va a usar el material. Si todavía es una idea, también nos sirve.",
    directTitle: "Contacto directo",
    phone: "Teléfono / WhatsApp",
    based: "Con base en Valencia",
  },
  footer: {
    tagline: "Estudio creativo de contenido y comunicación visual.",
    legal: "Aviso legal",
    privacy: "Privacidad",
    cookies: "Cookies",
    rights: "Todos los derechos reservados.",
  },
  notFound: { title: "Este plano no existe.", body: "La página que buscas no está o ha cambiado de sitio.", back: "Volver al inicio" },
  common: { backToWork: "Todo el trabajo", services: "Servicios", work: "Trabajo" },
};

type Copy = typeof es;

const en: Copy = {
  meta: {
    homeTitle: "24SHOOTS — Creative studio for content and visual communication · Valencia",
    homeDescription:
      "Creative studio for content and visual communication, based in Valencia. Film and photography for corporate events, brand content and campaigns.",
    orgDescription:
      "Creative studio for content and visual communication based in Valencia, Spain. Film and photography for corporate events, brand content and campaigns.",
  },
  nav: { work: "Work", services: "Services", studio: "Studio", contact: "Contact", cta: "Let’s talk", menu: "Menu", close: "Close", skip: "Skip to content", home: "Home", language: "Español", languageShort: "ES" },
  hero: {
    eyebrow: "Creative studio · Valencia",
    title: "Images with an idea.",
    lead: "Content and visual communication for brands: corporate events, brand content and campaigns. Conceived, filmed and edited by the same team.",
    primary: "Tell us about your project",
    secondary: "See the work",
    reelLabel: "Reel of recent work",
    pause: "Pause reel",
    play: "Play reel",
    shot: "Shot",
    viewCase: "View project",
  },
  work: {
    title: "Selected work",
    intro: "Five projects. Each one an important moment for an organisation, told in images.",
    all: "All work",
    view: "View project",
    count: (n: number) => `${String(n).padStart(2, "0")} projects`,
  },
  day: {
    kicker: "One day, all year",
    title: "An event lasts a day. The story of it lasts all year.",
    body: "An anniversary, a gala, a conference: moments an organisation prepares for months and that last a few hours. Our job is to make sure they can keep being told afterwards, on the website, on social media, in internal communications or in the next presentation.",
    sheetCaption: "Huhtamaki · 50th anniversary. Twelve shots from the same day.",
    fromOneShoot: "One shoot can produce",
    outputs: ["The event film", "Vertical cuts for social media", "A photo selection", "Short pieces for internal comms or press"],
  },
  servicesBlock: { title: "What we do", capabilities: "Filming · Drone · Photography · Editing · Colour · Sound · Social versions" },
  clients: {
    title: "Who we have worked with",
    agencies: "We also produce as part of event agencies’ and production companies’ teams.",
  },
  contactBlock: {
    title: "Tell us about your project.",
    lead: "What it is, when it is and what you need to say. A person from the team will reply.",
    direct: "Or write to us directly",
  },
  form: {
    name: "Name",
    email: "Email",
    company: "Company or organisation",
    type: "Type of project",
    types: ["Event", "Brand content", "Campaign", "Something else"],
    message: "What do you have in mind?",
    messageHint: "For example: company anniversary in June, around 300 people, we want a film and pieces for social media.",
    date: "Date or deadline, if any",
    optional: "optional",
    required: "required",
    submit: "Send",
    sending: "Sending…",
    privacy: "We will only use your details to reply to this enquiry.",
    privacyLink: "Privacy policy",
    successTitle: "Received.",
    success: (email: string) => `We will reply to ${email}. In the meantime, have a look at more work.`,
    errorTitle: "It could not be sent.",
    errorBody: "Write to us directly at",
    errors: {
      name: "Please enter your name.",
      email: "Please check the email address.",
      message: "Tell us a little more (at least 20 characters).",
      rate: "Too many attempts. Wait a minute or email us.",
      generic: "Sending failed.",
    },
    summary: "Please check the highlighted fields.",
  },
  case: {
    client: "Client",
    type: "Type",
    when: "Date",
    with: "With",
    format: "Format",
    play: "Play film",
    duration: "Length",
    shows: "What the film covers",
    stills: "Stills",
    next: "Next project",
    cta: "Have a moment like this coming up?",
    ctaButton: "Let’s talk",
    area: "Area",
  },
  servicesPage: {
    title: "Services",
    intro: "Three ways of working with us. In all of them, the same idea: images that communicate something specific.",
    problem: "The problem",
    approach: "How we do it",
    capabilities: "Capabilities",
    deliverables: "What you get",
    related: "Related work",
    faq: "Frequently asked questions",
    cta: "Tell us about your project",
  },
  studio: {
    title: "Studio",
    lead: "24SHOOTS is a creative studio for content and visual communication based in Valencia, Spain. We work for brands, institutions and event agencies: we conceive, film and edit film and photography that an organisation can use to tell what it does.",
    howTitle: "How we work",
    how: [
      { t: "Before", d: "We understand what needs telling, to whom and where it will be seen, before deciding how to film it." },
      { t: "During", d: "We film to an agreed plan: which moments matter, who needs to appear and which formats are needed." },
      { t: "After", d: "Editing, colour and sound designed for each channel: the main piece and every piece that comes out of it." },
    ],
    agenciesTitle: "For agencies and producers",
    agencies: "Part of our work is done inside the teams of event agencies and production companies. We take care of film and photography so they can focus on the event.",
    clientsTitle: "Clients",
  },
  contactPage: {
    title: "Tell us about your project",
    lead: "The more specific, the better: what it is, when, for whom and where the material will be used. If it is still just an idea, that works too.",
    directTitle: "Direct contact",
    phone: "Phone / WhatsApp",
    based: "Based in Valencia, Spain",
  },
  footer: {
    tagline: "Creative studio for content and visual communication.",
    legal: "Legal notice",
    privacy: "Privacy",
    cookies: "Cookies",
    rights: "All rights reserved.",
  },
  notFound: { title: "This shot doesn’t exist.", body: "The page you are looking for is not here or has moved.", back: "Back to home" },
  common: { backToWork: "All work", services: "Services", work: "Work" },
};

export const copy: Record<Locale, Copy> = { es, en };
export const t = (locale: Locale) => copy[locale];
