#!/usr/bin/env node
/**
 * After `opennextjs-cloudflare build`: keep files that Workers static assets cannot host
 * out of the upload. Full films (≈37 MB each) exceed the 25 MiB per-asset limit; they are
 * served from R2 instead (NEXT_PUBLIC_FILM_BASE, see docs/CLOUDFLARE.md).
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = new URL("../../", import.meta.url).pathname;
const ASSETS = join(ROOT, ".open-next/assets");
const LIMIT = 25 * 1024 * 1024;
const big = [];
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) walk(p);
    else if (s.size > LIMIT) big.push("/" + relative(ASSETS, p));
  }
};
walk(ASSETS);
writeFileSync(join(ASSETS, ".assetsignore"), ["# generated by scripts/cloudflare/post-build.mjs", "/media/*/film.mp4", ...big].join("\n") + "\n");
console.log(`assets: ignoring ${big.length} file(s) over 25 MiB + all /media/*/film.mp4 (served from R2)`);
if (!process.env.NEXT_PUBLIC_FILM_BASE) {
  console.warn("WARNING: NEXT_PUBLIC_FILM_BASE is not set — case pages will link films that are not deployed.");
}
